//
//  EmoStyleKit.h
//  emo
//
//  Created by Aviv Wolf on 1/28/15.
//  Copyright (c) 2015 Homage. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>



@interface EmoStyleKit : NSObject

// Colors
+ (UIColor*)colorRecorderRecordingButtonBG;
+ (UIColor*)colorAnswerPositive;
+ (UIColor*)colorAnswerNegative;
+ (UIColor*)colorDefaultBackground;

// Shadows
+ (NSShadow*)shadowSimple;

// Drawing Methods
+ (void)drawRecorderRecordButton;

@end



@interface NSShadow (PaintCodeAdditions)

+ (instancetype)shadowWithColor: (UIColor*)color offset: (CGSize)offset blurRadius: (CGFloat)blurRadius;
- (void)set;

@end
