source 'https://github.com/CocoaPods/Specs.git'
platform :ios,          '8.0'
pod 'AFNetworking',     '~> 2.5.0'
pod 'Mixpanel', '~> 2.7.0'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'SDWebImage', '~> 3.7.0'
pod 'NSLogger', '~> 1.5'
pod 'FLAnimatedImage', '~> 1.0'
pod 'MGBenchmark', '~> 0.3'
pod 'AFSoundManager'
pod 'Toast', '~> 2.4'
pod 'zipzap', '~> 8.0'
pod 'Facebook-iOS-SDK', '~> 3.23', :inhibit_warnings => true