source 'https://github.com/CocoaPods/Specs.git'
platform :ios,          '8.0'
pod 'AFNetworking',     '~> 2.5.0'
pod 'Mixpanel', '~> 2.7.0'
pod 'Facebook-iOS-SDK', '~> 3.22.0'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'SDWebImage', '~> 3.7.0'